---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-world.fullname" . }}-nginx-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |-
{{ .Values.nginxConfig | indent 4 }}
