apiVersion: kuttl.dev/v1beta1
kind: TestStep
apply:
- file: ../../../pod-security/baseline/disallow-host-ports-range/pod-good.yaml
  shouldFail: false
- file: ../../../pod-security/baseline/disallow-host-ports-range/pod-bad.yaml
  shouldFail: true
- file: ../../../pod-security/baseline/disallow-host-ports-range/podcontroller-good.yaml
  shouldFail: false
- file: ../../../pod-security/baseline/disallow-host-ports-range/podcontroller-bad.yaml
  shouldFail: true
