name: cdw-tag

on:
  workflow_dispatch:
    inputs:
      incr:
        type: choice
        description: Semantic version increment
        default: prerelease
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tag:
    uses: cdwlabs/managed-actions/.github/workflows/tag.yml@main
    with:
      incr: ${{ inputs.incr }}
